/**
 * phaseMatrix.ts
 * Section 10 — Phase MD×AD Combined Names (9×9 = 81 combinations)
 *
 * Format: { name, summary, opportunity, risk, avoidTag }
 */

import type { PlanetKey } from "@/lib/types/astrology";

export interface PhaseDescriptor {
  name: string;
  summary: string;
  opportunity: string;
  risk: string;
  /** Short 1-3 word label used in the "avoid: ___" tag on the dashboard. */
  avoidTag: string;
}

type PhaseMatrix = Record<PlanetKey, Record<PlanetKey, PhaseDescriptor>>;

// Helper to build entries cleanly
function phase(
  name: string,
  summary: string,
  opportunity: string,
  risk: string,
  avoidTag: string
): PhaseDescriptor {
  return { name, summary, opportunity, risk, avoidTag };
}

export const PHASE_MATRIX: PhaseMatrix = {
  // ── KETU Maha Dasha ───────────────────────────────────────────────────────
  ketu: {
    ketu:    phase("deep dissolution",
      "Everything non-essential is being released simultaneously. This is not breakdown: it is completion.",
      "Sit with what remains after the stripping. Clarity earned here is permanent.",
      "Resist re-attaching to what is in the process of falling away.",
      "re-attachment"),
    venus:   phase("letting go of what you loved",
      "The period asks you to release an attachment: to a person, a comfort, or a self-image.",
      "Let pleasure teach you what it can without grasping at it.",
      "Holding on to beauty or ease during dissolution prolongs the discomfort.",
      "grasping"),
    sun:     phase("burning the old identity",
      "Who you thought you were is being revised at the root level.",
      "Let the authority you have earned speak. Drop what was inherited.",
      "Performing the old role while it is being dismantled creates friction.",
      "old roles"),
    moon:    phase("grief finds its floor",
      "Feeling moves through you more than it moves you. This has a bottom.",
      "Let emotional truth surface without dramatizing it.",
      "Suppression or overflow both extend the cycle.",
      "suppression"),
    mars:    phase("cutting what cannot come",
      "Action serves release, not acquisition. Things end cleanly or they end badly.",
      "Move only where motion creates genuine space.",
      "Force applied here tends to accelerate what you are trying to slow.",
      "force"),
    rahu:    phase("severance and illusion",
      "You are being separated from an inflated version of what you wanted.",
      "Stay with what is real after the amplification fades.",
      "Following the noise will land you somewhere you did not intend.",
      "distraction"),
    jupiter: phase("loss that opens",
      "What you lose in this period reveals room you did not know was blocked.",
      "Allow wisdom to arrive through contraction, not expansion.",
      "Forcing growth before the space has cleared will be messy.",
      "forcing growth"),
    saturn:  phase("the long emptying",
      "Patience is not optional here. The release moves at its own pace.",
      "Discipline your response to what cannot be rushed.",
      "Pushing against the pace of this period adds weight it does not need.",
      "resistance"),
    mercury: phase("root and dissolve",
      "Analysis serves release. Understand what is ending, then let it end.",
      "Discern carefully, then trust the dissolution.",
      "Over-thinking the release is its own form of holding on.",
      "overthinking"),
  },

  // ── VENUS Maha Dasha ──────────────────────────────────────────────────────
  venus: {
    ketu:    phase("release what no longer delights",
      "Pleasure that has become habit is being examined. What remains is real.",
      "Let enjoyment become more precise: fewer things, more depth.",
      "Holding onto comfort at the cost of authenticity will hollow out the period.",
      "comfort-clinging"),
    venus:   phase("pure receptivity",
      "The capacity to receive (beauty, connection, rest) is at its fullest.",
      "Lean into what sustains and nourishes without guilt.",
      "Overindulgence without reflection wastes the softness this period offers.",
      "overindulgence"),
    sun:     phase("pleasure meets purpose",
      "Enjoyment and direction can co-exist. The period rewards beauty that also functions.",
      "Do work that feels worth doing and looks worth seeing.",
      "Separating pleasure from purpose creates a split this period does not support.",
      "splitting"),
    moon:    phase("soft and steady",
      "Emotional ease and aesthetic sensibility are both available. Use them.",
      "Invest in what nourishes home, body, and connection.",
      "Restlessness or overreach will disturb a period that rewards stillness.",
      "overreach"),
    mars:    phase("desire in motion",
      "Wanting something and moving toward it are aligned. Act.",
      "Bring Venus' warmth to Mars' direction: desire with craft.",
      "Desire without refinement can create entanglements that outlast the impulse.",
      "unrefined desire"),
    rahu:    phase("amplified longing",
      "What you want is magnified. That is information about your nature.",
      "Use the amplification to clarify, not to acquire at scale.",
      "Rahu's distortion can make temporary satisfaction look like permanent arrival.",
      "false arrival"),
    jupiter: phase("generosity expanding",
      "The capacity to give and receive is large. Use it to build what lasts.",
      "Invest in what multiplies: relationships, knowledge, beauty.",
      "Abundance without discernment creates excess that needs cleanup.",
      "excess"),
    saturn:  phase("patient beauty",
      "What you build for lasting satisfaction moves slowly. Let it.",
      "Create things designed to be used for decades, not days.",
      "Rushing toward pleasure in a Saturn sub-period costs more than it returns.",
      "rushing"),
    mercury: phase("refine and receive",
      "Discernment and receptivity together. The period rewards careful taste.",
      "Refine what you produce and receive what is offered. Both matter.",
      "Analysis without softness or softness without precision both miss this period's gift.",
      "imbalance"),
  },

  // ── SUN Maha Dasha ────────────────────────────────────────────────────────
  sun: {
    sun:     phase("pure authority",
      "The self is most clearly expressed. Visibility without effort.",
      "Step into your role fully. This is the moment you were built for.",
      "Overreach or performance without substance will erode what is earned here.",
      "overreach"),
    moon:    phase("self meeting feeling",
      "Authority and emotional truth are in conversation. Both want expression.",
      "Let the inner life inform how you lead. It sharpens rather than softens it.",
      "Suppressing feeling in favor of presentation creates a gap others will sense.",
      "suppression"),
    mars:    phase("force and focus",
      "Clarity of direction and willingness to act are both available.",
      "Move decisively. The timing is better than it looks from the outside.",
      "Aggression without direction burns the same energy as discipline with it.",
      "misdirection"),
    rahu:    phase("amplified visibility",
      "Your presence is enlarged. That creates both opportunity and exposure.",
      "Use the visibility to do work that deserves to be seen.",
      "Rahu amplifies what is real but also what is performed. The difference shows.",
      "performance"),
    jupiter: phase("authority meeting wisdom",
      "Leadership informed by perspective. The combination carries weight.",
      "Bring generosity to your authority. It multiplies rather than divides.",
      "Arrogance or contraction in a generous period is a waste.",
      "arrogance"),
    saturn:  phase("discipline of leadership",
      "Authority earned through consistency. Not given, not assumed.",
      "Show up repeatedly at a level that does not require explanation.",
      "Shortcut the process and the authority does not hold.",
      "shortcuts"),
    mercury: phase("clarity and precision",
      "The period rewards clear thinking delivered cleanly.",
      "Communicate with precision. Edit before you speak.",
      "Complexity performed as sophistication does not land well here.",
      "overcomplication"),
    ketu:    phase("shedding the public mask",
      "The version of you that others recognize is being revised at depth.",
      "Let the stripping clarify what remains after the performance.",
      "Resisting the revision while Sun energy is still prominent creates a long middle.",
      "resistance"),
    venus:   phase("warmth and recognition",
      "Being seen and appreciated for what you genuinely are.",
      "Let warmth inform how authority is exercised. It does not weaken it.",
      "Seeking recognition without offering warmth creates the appearance without the substance.",
      "hollow recognition"),
  },

  // ── MOON Maha Dasha ───────────────────────────────────────────────────────
  moon: {
    moon:    phase("pure feeling",
      "Emotional signal is the primary navigation instrument right now.",
      "Trust what you feel more than what you can defend rationally.",
      "Overriding emotion with logic in this period tends to produce regret.",
      "suppression"),
    mars:    phase("emotion under pressure",
      "Feeling and action are in tension. Both want the wheel.",
      "Let emotion inform direction, then move with it, not against it.",
      "Acting from frustration or suppressing action from fear both miss the window.",
      "frustration"),
    rahu:    phase("flooded senses",
      "Input is amplified. Sensory and emotional information is at high volume.",
      "Slow down the processing. Let the flood settle before deciding.",
      "Rahu's distortion in a Moon period can make temporary states feel permanent.",
      "false permanence"),
    jupiter: phase("emotional generosity",
      "Feeling and wisdom are available at the same time. Rare combination.",
      "Give from fullness. The period supports genuine expansion.",
      "Generosity without boundaries drains the reservoir.",
      "overextension"),
    saturn:  phase("cold but clear",
      "Emotion is present but disciplined. What you feel is real but not controlling.",
      "Use the clarity that comes with emotional discipline to build something lasting.",
      "Coldness without care creates structures that people cannot live in.",
      "coldness"),
    mercury: phase("mind listens to heart",
      "Analysis and feeling are in conversation. Let feeling lead.",
      "Communicate from the felt sense, not the defended position.",
      "Intellectualizing emotion in this period delays what it is trying to tell you.",
      "intellectualizing"),
    ketu:    phase("feeling dissolves",
      "Attachment to emotional outcomes is releasing. This is movement.",
      "Let go of the version of feeling you thought was permanent.",
      "Fighting the release intensifies what you are trying to pass through.",
      "resistance"),
    venus:   phase("comfort and ease",
      "A period of genuine softness. Let it restore rather than challenge.",
      "Invest in what nourishes without performing productivity.",
      "Using ease as an excuse to avoid necessary movement will compound later.",
      "avoidance"),
    sun:     phase("showing the inner life",
      "What is felt is also what is visible. The private is becoming public.",
      "Let authenticity drive visibility. It earns more than the performed version.",
      "Hiding the interior during a Moon-Sun period creates a split that shows.",
      "hiding"),
  },

  // ── MARS Maha Dasha ───────────────────────────────────────────────────────
  mars: {
    mars:    phase("pure action",
      "The capacity to move is at its maximum. Use it with direction.",
      "Act decisively on what has been deferred. The window is open.",
      "Action without aim in this period creates damage rather than momentum.",
      "aimlessness"),
    rahu:    phase("dangerous momentum",
      "The drive to move is amplified beyond what is visible or safe.",
      "Channel the force into one target. Dispersal is expensive.",
      "Rahu's distortion can make reckless speed feel like confidence.",
      "recklessness"),
    jupiter: phase("righteous force",
      "Action informed by principle. Movement in a direction worth moving.",
      "Build something worth building with the force available.",
      "Excess force even in a good direction leaves wreckage.",
      "excess force"),
    saturn:  phase("tested endurance",
      "Mars wants to move. Saturn slows the pace. The tension builds something real.",
      "Stay with the process after the initial push. The work outlasts the launch.",
      "Forcing pace against Saturn's resistance fractures what you are trying to build.",
      "forcing pace"),
    mercury: phase("surgical action",
      "Precision replaces force. The right move at the right moment.",
      "Think before you act, then act cleanly and completely.",
      "Hesitation is not the risk. Acting before you have the full picture is.",
      "premature action"),
    ketu:    phase("the cut that ends it",
      "Action serves release. Something is concluding and it needs a clean cut.",
      "Make the difficult move that stops the drag.",
      "Delay prolongs what is already draining you.",
      "delay"),
    venus:   phase("passion in form",
      "Desire wants to create something beautiful. Let it.",
      "Bring craft to what you care about. Form matters here.",
      "Desire without form creates intensity without direction.",
      "formless desire"),
    sun:     phase("courage visible",
      "Action and visibility coincide. What you do is being seen.",
      "Act with the clarity that you would be comfortable defending.",
      "Recklessness under a spotlight costs more than it would in private.",
      "recklessness"),
    moon:    phase("fire meets water",
      "The impulse to act and the need to feel are not as opposed as they seem.",
      "Let feeling inform direction without softening resolve.",
      "Suppression of either side creates pressure that finds the wrong exit.",
      "suppression"),
  },

  // ── RAHU Maha Dasha ───────────────────────────────────────────────────────
  rahu: {
    rahu:    phase("peak amplification",
      "Everything is louder, larger, and more distorted than it appears.",
      "Use the amplification to see clearly, then scale back before committing.",
      "What feels like the full picture in a Rahu period is reliably incomplete.",
      "false certainty"),
    jupiter: phase("expansion seeking wisdom",
      "The desire to grow is being met by genuine perspective. Rare alignment.",
      "Expand into substance. The wisdom available now is real.",
      "Growth without grounding in a Rahu-Jupiter period can still overshoot.",
      "overreach"),
    saturn:  phase("desire meets wall",
      "What Rahu wants, Saturn limits. The friction is purposeful.",
      "Discipline the amplification. What survives the wall is real.",
      "Fighting the restriction burns energy that could be building something.",
      "resistance"),
    mercury: phase("signal and noise",
      "Enormous amounts of information are available. Most of it is static.",
      "Filter ruthlessly. The real signal is quieter than the noise.",
      "Acting on the loudest input in a Rahu period is the most common mistake.",
      "noise-chasing"),
    ketu:    phase("the axis of illusion",
      "Rahu's amplification and Ketu's dissolution are active at the same time.",
      "Hold both (what you are gaining and what you are releasing) without privileging either.",
      "The polarization of this period intensifies. A center point is necessary.",
      "polarization"),
    venus:   phase("seductive overreach",
      "What you desire is amplified to the point of distortion.",
      "Enjoy what is real in the offering without extending past your actual capacity.",
      "Rahu's distortion through Venus can make temporary pleasure look like permanent arrival.",
      "overextension"),
    sun:     phase("public ambition",
      "Visibility and the desire for recognition are at maximum.",
      "Let substance lead. The audience will judge the work, not the performance.",
      "Rahu's amplification can make attention feel like approval. They are not the same.",
      "false approval"),
    moon:    phase("restless wanting",
      "Emotional need is amplified and unsettled. This is information about the gap.",
      "Identify what you actually need, separate from what Rahu is amplifying.",
      "Acting on amplified emotional need in this period tends to create binds.",
      "emotional binds"),
    mars:    phase("dangerous drive",
      "Force and amplification together. High capacity for both creation and damage.",
      "Aim carefully before you act. The force available is real.",
      "Rahu's distortion and Mars' aggression together make restraint necessary, not optional.",
      "recklessness"),
  },

  // ── JUPITER Maha Dasha ────────────────────────────────────────────────────
  jupiter: {
    jupiter: phase("pure grace",
      "Expansion and wisdom are available without the usual cost.",
      "Invest generously in what you believe in. The period supports it.",
      "Grace without discernment still produces excess. Wisdom requires selection.",
      "indiscriminate grace"),
    saturn:  phase("discipline meeting grace",
      "Expansion that is also accountable. Growth that holds.",
      "Build slowly and build well. What is made here is durable.",
      "Forcing the pace of Jupiter through Saturn's timeline defeats the combination.",
      "forcing pace"),
    mercury: phase("wide meets sharp",
      "Broad perspective and analytical precision together.",
      "Think expansively, then apply it precisely. Both are available.",
      "Analysis without vision or vision without detail both miss this period's gift.",
      "narrow vision"),
    ketu:    phase("wisdom through loss",
      "Understanding that arrives through release rather than acquisition.",
      "Let the teaching complete itself. What you lose clarifies what remains.",
      "Resisting the dissolution while Jupiter's wisdom is available delays the insight.",
      "resistance"),
    venus:   phase("expansive warmth",
      "Generosity and beauty at the same time. A period for genuine flourishing.",
      "Invest in what is nourishing and let yourself receive what is offered.",
      "Overflow without direction still creates mess.",
      "excess"),
    sun:     phase("generous authority",
      "Leadership that gives rather than takes. Rare and effective.",
      "Use the period to expand what is under your care, not just what you control.",
      "Authority without generosity in a Jupiter period is a waste of the alignment.",
      "contraction"),
    moon:    phase("open-hearted depth",
      "Feeling and wisdom are both available. Let them inform each other.",
      "Be present to what is felt without being overwhelmed by it.",
      "Emotional open-heartedness without discernment can absorb more than is healthy.",
      "overwhelm"),
    mars:    phase("righteous courage",
      "Principle meets action. Movement in a direction worth committing to.",
      "Act from your conviction. The period supports it.",
      "Righteousness that becomes rigidity defeats the expansive nature of this period.",
      "rigidity"),
    rahu:    phase("the guru and the seduction",
      "Wisdom is available but so is the amplified version of what you want.",
      "Choose the teaching over the shortcut. They are usually not the same path.",
      "Rahu's distortion can make desire look like guidance. They are different.",
      "self-deception"),
  },

  // ── SATURN Maha Dasha ─────────────────────────────────────────────────────
  saturn: {
    saturn:  phase("weight and structure",
      "Everything takes longer and costs more. This is not punishment.",
      "Build something that would hold up in twenty years. That is the question this period asks.",
      "Rushing anything in a double Saturn period will require rebuilding.",
      "rushing"),
    mercury: phase("precision and patience",
      "Analysis in service of long-term structure. Slow thinking for durable results.",
      "Refine the thinking before you build the thing. Order matters.",
      "Analysis without patience in a Saturn period produces half-built structures.",
      "impatience"),
    ketu:    phase("the long release",
      "Something structural is being dismantled slowly and with purpose.",
      "Let the release move at its own pace. What is left will hold.",
      "Fighting the slowness of this dissolution compounds the weight.",
      "resistance"),
    venus:   phase("slow beauty",
      "What is beautiful here is not decorative. It is earned and durable.",
      "Create things that will still carry meaning in a decade.",
      "Seeking pleasure as relief from Saturn's weight only extends the period.",
      "escape"),
    sun:     phase("hard earned authority",
      "Visibility and respect come through sustained demonstration, not announcement.",
      "Stay at the work. The recognition follows the consistency.",
      "Shortcuts to visibility in a Saturn period will not hold.",
      "shortcuts"),
    moon:    phase("cold clarity",
      "Emotional truth without sentiment. A period for honest reckoning.",
      "Let what is clear be clear, even if it is hard.",
      "Coldness that becomes distance damages what Saturn is trying to build.",
      "coldness"),
    mars:    phase("pressure and edge",
      "The drive to act is slowed and tested. What endures is real.",
      "Bring discipline to your aggression. The edge is useful when it is precise.",
      "Force without patience in a Saturn period breaks more than it builds.",
      "force"),
    rahu:    phase("ambition under weight",
      "What you want is enlarged but the path is obstructed and slow.",
      "Discipline the ambition. What is built under this pressure will outlast it.",
      "Rahu's amplification of desire against Saturn's weight creates compulsive cycles.",
      "compulsion"),
    jupiter: phase("patient expansion",
      "Growth is available but will not be rushed. Build something worth waiting for.",
      "Invest in depth. What is cultivated slowly in this period compounds well.",
      "Impatience with Jupiter's timeline under Saturn will truncate what is being built.",
      "impatience"),
  },

  // ── MERCURY Maha Dasha ────────────────────────────────────────────────────
  mercury: {
    mercury: phase("pure signal",
      "Clarity and discernment are at their maximum. Use them.",
      "Think, communicate, and decide with the full range of your analysis.",
      "Over-analysis in a Mercury period can paralyze what clarity should activate.",
      "paralysis"),
    ketu:    phase("root and dissolve",
      "Analysis serves release. Understanding what is ending, then letting it end.",
      "Discern carefully what no longer belongs, then let it go cleanly.",
      "Over-thinking the dissolution is a form of holding on.",
      "overthinking"),
    venus:   phase("refine and receive",
      "Discernment and receptivity in productive tension.",
      "Refine what you produce. Receive what is genuinely offered.",
      "Neither analysis alone nor receptivity alone captures this period's combination.",
      "imbalance"),
    sun:     phase("signal and authority",
      "Clarity in service of direction. Communication that moves things.",
      "Speak with precision on what matters most.",
      "Clarity without warmth creates efficient but empty exchange.",
      "coldness"),
    moon:    phase("mind and feeling converging",
      "Analysis and emotion are in dialogue. Let both speak.",
      "Communicate the felt sense alongside the reasoned position.",
      "Prioritizing logic over feeling or feeling over logic misses the convergence.",
      "imbalance"),
    mars:    phase("discernment under pressure",
      "Thinking clearly when there is pressure to act fast.",
      "Slow the analysis just enough to act with precision.",
      "Speed without thought in a Mercury period creates cleanup.",
      "hasty action"),
    rahu:    phase("signal and noise",
      "An enormous amount of information is available. Almost none of it is signal.",
      "Filter aggressively. The real answer is quieter than the data.",
      "Acting on the volume of information rather than the quality is the main risk.",
      "noise-chasing"),
    jupiter: phase("sharp meets wide",
      "Precision in service of understanding. Analysis that expands rather than limits.",
      "Bring Mercury's detail to Jupiter's vision. The combination is rare.",
      "Analysis without perspective produces accurate but airless conclusions.",
      "narrow analysis"),
    saturn:  phase("precision and patience",
      "Slow, careful, deliberate thinking in service of durable results.",
      "Think fully before building. The structure should survive the builder.",
      "Impatience with Mercury's usual speed under Saturn produces unstable conclusions.",
      "impatience"),
  },
};

/**
 * Retrieves the phase descriptor for a given MD lord × AD lord combination.
 */
export function getPhaseDescriptor(mdLord: PlanetKey, adLord: PlanetKey): PhaseDescriptor {
  return PHASE_MATRIX[mdLord]?.[adLord] ?? {
    name: `${mdLord} / ${adLord}`,
    summary: "A period defined by the combined qualities of these two influences.",
    opportunity: "Work with what each graha brings without forcing the combination.",
    risk: "Ignoring the secondary influence costs the richness of the period.",
    avoidTag: "resistance",
  };
}
