"use client";

import BackLink from "@/components/ui/BackLink";
import DecorativeDivider from "@/components/svg/DecorativeDivider";

export default function LegalPage() {
  return (
    <main className="min-h-screen px-6 py-8" style={{ maxWidth: "720px", margin: "0 auto" }}>
      <BackLink />

      <article className="mt-4">
        <h1
          className="text-2xl font-normal"
          style={{ fontFamily: "var(--font-playfair-display)", color: "#2C2418" }}
        >
          Privacy Policy & Terms of Service
        </h1>

        <div className="mt-6">
          <DecorativeDivider width={200} opacity={0.2} />
        </div>

        <section className="mt-8 space-y-8">
          <div>
            <h2
              className="text-sm uppercase tracking-wider mb-3"
              style={{ fontFamily: "var(--font-inter-var)", color: "#8A7240" }}
            >
              Privacy Policy
            </h2>
            <div
              className="space-y-4 text-sm leading-relaxed"
              style={{ fontFamily: "var(--font-inter-var)", color: "#2C2418" }}
            >
              <p>
                <strong>Data Storage:</strong> All personal information you provide (name, date of birth, time of birth, and place of birth) is stored locally on your device. We do not transmit your personal data to any external servers.
              </p>
              <p>
                <strong>No Third-Party Tracking:</strong> Kaal does not use any analytics, cookies, or tracking technologies. Your usage patterns remain completely private.
              </p>
              <p>
                <strong>Data Control:</strong> You can delete all stored data at any time through the settings menu on the dashboard. Clearing your profile removes all personal information from your device.
              </p>
            </div>
          </div>

          <div>
            <h2
              className="text-sm uppercase tracking-wider mb-3"
              style={{ fontFamily: "var(--font-inter-var)", color: "#8A7240" }}
            >
              Terms of Service
            </h2>
            <div
              className="space-y-4 text-sm leading-relaxed"
              style={{ fontFamily: "var(--font-inter-var)", color: "#2C2418" }}
            >
              <p>
                <strong>Entertainment & Educational Purpose:</strong> Kaal is designed for entertainment and educational purposes only. The insights provided are based on traditional timing systems and should not be used as the sole basis for major life decisions.
              </p>
              <p>
                <strong>No Professional Advice:</strong> The information generated by Kaal does not constitute professional advice of any kind. For medical, legal, financial, or career decisions, please consult qualified professionals.
              </p>
              <p>
                <strong>Accuracy:</strong> While we strive for accuracy in our calculations, timing systems vary across traditions. Results are approximations and should be viewed as one perspective among many.
              </p>
              <p>
                <strong>Acceptance:</strong> By using Kaal, you acknowledge that you understand this app is for entertainment and educational purposes only, and you accept these terms.
              </p>
            </div>
          </div>
        </section>

        <div className="mt-12 pt-8 border-t border-[#9C9488]/20">
          <p
            className="text-xs text-center"
            style={{ fontFamily: "var(--font-inter-var)", color: "#7A7469" }}
          >
            Last updated: April 2026
          </p>
        </div>
      </article>
    </main>
  );
}